# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_taken',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
