# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_quiz_time_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[(b'i', b'In Progress'), (b'r', b'In Review'), (b'p', b'Published')], default=b'i', max_length=1),
        ),
    ]
